### PR TITLE
Remove parameter ppm from filterPrecursorMz and code cleanup

### PR DESCRIPTION
**Pull request by jorainer**
- Remove the `ppm` parameter from the `filterPrecursorMz` function that expects now a `numeric(2)` with parameter `mz` (issue #57).
- Remove no longer needed binning utility functions (issue #56).

### CODE REVIEW

**Comment by jorainer** [comment]
No idea why I get now the check error - will investigate and fix.

**Comment by jorainer** [comment]
Hm `S4Vectors::DataFrame` returns now a `DFrame` instead of a `DataFrame`!

```r
> class(S4Vectors::DataFrame())
[1] "DFrame"
attr(,"package")
[1] "S4Vectors"

```

**Comment by lgatto** [comment]
Indeed, but only in devel. That is confusing. I don't remember seeing this on the developer mailing list. It's very recent:

```
Author: Hervé Pagès <hpages@fredhutch.org>
Date:   Tue Aug 20 19:02:00 2019 -0700

    DataFrame() now returns a DFrame instance
    
    Other changes:
    
    o All coercion methods to DataFrame now return a DFrame instance instead
      of a DataFrame instance. The goal being that, from now on, any code that
      used to produce a DataFrame instance will instead produce a DFrame
      instance. This is achieved by having the DataFrame() constructor and all
      the coercion methods to DataFrame return a DFrame instance instead of a
      DataFrame instance.
    
    o show() still prints a header line that says "DataFrame with M rows and
      N columns" on a DFrame instance. This is in order to make the migration
      from DataFrame to DFrame as transparent as possible for the end-user
      (although s/he'll notice the change when calling class() on the object).
    
    o Calling updateObject() on a DataFrame instance will turn it into a DFrame
      instance. Also calling it on a Vector derivative that has its metadata
      columns in a DataFrame instance will return an object where the metadata
      columns are in a DFrame instance. This is to facilitate the migration of
      serialized DataFrame instances or serialized Vector derivatives containing
      DataFrame instances.
    
    o 'mcols(x)' and 'mcols(x) <- value' now pass 'x@elementMetadata' and
      'value' (respectively) thru updateObject(). This reduces the risk of
      propagating DataFrame instances by automatically replacing them
      on-the-fly with DFrame instances.

commit 36837bdf8ba55a3e12f8f55cb3cf75c45b045d77
Author: Hervé Pagès <hpages@fredhutch.org>
Date:   Fri Aug 16 08:20:25 2019 -0700

    Add DFrame class
    
    Just a direct DataFrame extension with no additional slot for now. Once all
    serialized DataFrame instances are replaced with DFrame instances (which
    will take several BioC release cycles) we'll be able to move the DataFrame
    slots from the DataFrame class definition to the DFrame class definition.
    The final goal is to have DataFrame become a virtual class with no slots
    that only extends DataTable, and DFrame a concrete DataFrame and SimpleList
    subclass that has the same slots as the current DataFrame class.
```

**Comment by lgatto** [comment]
For the record, @hpages announcing the [`DFrame` change](https://stat.ethz.ch/pipermail/bioc-devel/2019-August/015416.html) on bioc-devel. This is actually excellent news for our back-end work.

**Comment by lgatto** [comment]
For the record, @hpages announcing the [`DFrame` change](https://stat.ethz.ch/pipermail/bioc-devel/2019-August/015416.html) on bioc-devel. This is actually excellent news for our back-end work.

**Pull request merged**
