### PR TITLE
fix: replacing spectraData on Spectra does not remove m/z

### PR DESCRIPTION
**Pull request by jorainer**
- Avoid removing m/z and intensity values when calling
  `spectraData<-,Spectra` (issue #146).

### CODE REVIEW

**Comment by jorainer** [comment]
An additional change in this PR is that I moved most of the `filter*` functions from `MsBackendDataFrame` to `MsBackend` hence avoiding the need to re-implement these methods for all new backends.

**Review by lgatto — APPROVED** [review]

**Comment by jorainer** [comment]
@lgatto , did you already push to Bioconductor?

**Comment by lgatto** [comment]
Was about to, but it looks like you have just done it.

**Comment by jorainer** [comment]
But there are some strange things - like the github and bioconductor masters are not in sync - please see PR #148 (please don't merge that one!).

**Pull request merged**
